"use strict";
exports.__esModule = true;
exports.vegetable = exports.tea = exports.sushi = exports.starch = exports.spice = exports.seafood = exports.protein = exports.poison = exports.pasta = exports.other = exports.oil = exports.nut = exports.meat = exports.grain = exports.fungus = exports.fruit = exports.fish = exports.egg = exports.dairy = exports.berry = exports.baking = exports.alcohol = void 0;
exports.alcohol = [];
exports.baking = [];
exports.berry = [];
exports.dairy = [];
exports.egg = [];
exports.fish = [];
exports.fruit = [];
exports.fungus = [];
exports.grain = [];
exports.meat = [];
exports.nut = [];
exports.oil = [];
exports.other = [];
exports.pasta = [];
exports.poison = [];
exports.protein = [];
exports.seafood = [];
exports.spice = [];
exports.starch = [];
exports.sushi = [];
exports.tea = [];
exports.vegetable = [];
